[build]
target = "./armv7a-rpi-none-eabihf.json"

[target."cfg(all())"]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--gc-sections",
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
